### ISSUE TITLE
So how to start?

### ISSUE THREAD

**Issue by ongxiang** [OngKaiLun/Wonderpet#1]
Anybody know?

**Comment by kenfengchan** [comment]
1. Get a computer.
2. Get an Internet connection.
3. Ensure there is a web browser and/or a word processor.
4. Start doing.

**Comment by ongxiang** [comment]
So what's the 5th step?

**Comment by vijayo** [comment]
Bro ... go ask the tutor

**Comment by ChooChyauHoong** [comment]
Let check what our system required.

**Comment by ongxiang** [comment]
Hahahah thanks guys
